require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - debug.rb
    - dev/**/*
    - tmp/**/*

Security/Eval:
  Exclude:
    - 'lib/docspec/example.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'lib/docspec/cli.rb'